### ISSUE TITLE
Player is able to jump onto the frame of a door, potentially causing problems for AI

### ISSUE THREAD

**Issue by MichaelFar** [ProjectCGC/Hyponic-Biotic-Outbreak#37]
Description:

The door leading to the first encounter with the AI can be jumped on, Potentially leading to abuse of the AI.

Steps to Reproduce:

1. Using Unreal 5.3.2, load Hyponic-Biotic-Outbreak

2. Select the level L_Demo_Pre_Alpha and click the play icon on the header bar

3. While controlling the player pawn, proceed through the doors to the next room

4. Locate the door to the left

5. Jump onto back of the chair perpendicular to the door

6. Jump onto the red locked door

Expected Results:

Player is forbidden from accessing unintended parts of the geometry

Actual Results:

Player is able to jump onto the frame of the door, potentially causing issues with gameplay elements such as AI

See attached video:

https://github.com/user-attachments/assets/ef1f6d66-16be-4294-b8ef-64b4a87a0974

**Comment by ElsFouche** [comment]
During our transition from Wwise to FMOD certain blueprints failed to compile. There is a known bug with Unreal where blueprints that fail to compile will, in certain circumstances, lose their transform information. This occurred with the doors, resulting in them appearing as default cubes. These cubes would normally be more...door shaped for this blockout, resulting in the player being unable to jump on top of them. 

Solution: correct the transform data on the bugged objects. This will be completed in a coming bugfix.

**Comment by ElsFouche** [comment]
Door geometry has been corrected in the most recent stable build.
